import fs from 'fs/promises';
import { createReadStream, openSync, constants } from 'fs';
import path from 'path';
import { createHash, randomUUID } from 'crypto';
import { Readable, Transform } from 'stream';
import { pipeline } from 'stream/promises';

export const FILE_MAX_BYTES = 20 * 1024 * 1024;
export const FILE_ID = /^[a-f0-9]{64}$/;
export const FILE_TOTAL_MS = 120_000;
export const FILE_IDLE_MS = 20_000;

export function fileLimit(value?: number): number {
  if (value === undefined) return FILE_MAX_BYTES;
  if (!Number.isSafeInteger(value) || value <= 0 || value > FILE_MAX_BYTES) throw new Error('File limit must be between 1 byte and 20 MiB.');
  return value;
}

export function displayName(value: unknown): string {
  return typeof value === 'string' ? value.replace(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/g, '').slice(0, 200) || 'attachment' : 'attachment';
}

/** Every directory and filename is owned and generated by this feature. */
export async function privateDirectory(directory: string): Promise<void> {
  await fs.mkdir(directory, { recursive: true, mode: 0o700 });
  const stat = await fs.lstat(directory);
  if (!stat.isDirectory() || stat.isSymbolicLink() || await fs.realpath(directory) !== path.resolve(directory)) throw new Error('Unsafe attachment directory.');
  if (process.getuid && stat.uid !== process.getuid()) throw new Error('Attachment directory belongs to another user.');
  await fs.chmod(directory, 0o700);
}

export async function atomicJson(filename: string, value: unknown): Promise<void> {
  await privateDirectory(path.dirname(filename));
  const temporary = `${filename}.${randomUUID()}.tmp`;
  try {
    await fs.writeFile(temporary, JSON.stringify(value), { flag: 'wx', mode: 0o600 });
    await fs.rename(temporary, filename);
  } finally { await fs.rm(temporary, { force: true }); }
}

/** The limit applies to actual bytes, independent of headers and advertised size. */
export async function saveStream(
  source: Readable, filename: string, maxBytes: number, signal: AbortSignal,
  expected?: { size: number; sha256: string },
): Promise<{ size: number; sha256: string }> {
  let size = 0;
  const hash = createHash('sha256');
  let idle: NodeJS.Timeout;
  const refresh = () => {
    clearTimeout(idle);
    idle = setTimeout(() => source.destroy(new Error('File download stalled.')), FILE_IDLE_MS);
    idle.unref();
  };
  const meter = new Transform({
    transform(chunk: Buffer, _encoding, callback) {
      size += chunk.length;
      if (size > maxBytes) { callback(new Error(`File exceeds the ${maxBytes / 1024 / 1024} MiB limit.`)); return; }
      hash.update(chunk);
      refresh();
      callback(null, chunk);
    },
  });
  refresh();
  // A network stream can fail while opening the destination, before pipeline owns it.
  let sourceError: Error | undefined;
  const captureError = (error: Error) => { sourceError = error; };
  source.on('error', captureError);
  let handle: Awaited<ReturnType<typeof fs.open>> | undefined;
  try {
    handle = await fs.open(filename, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | constants.O_NOFOLLOW, 0o600);
    if (sourceError) throw sourceError;
    await pipeline(source, meter, handle.createWriteStream(), { signal });
    const sha256 = hash.digest('hex');
    if (expected && (expected.size !== size || expected.sha256 !== sha256)) throw new Error('File integrity check failed (size or SHA-256 mismatch).');
    return { size, sha256 };
  } catch (error) {
    source.destroy();
    if (handle) await fs.rm(filename, { force: true });
    throw error;
  } finally {
    clearTimeout(idle!); await handle?.close().catch(() => {});
    // Leave the error observer attached until destroy's deferred error has fired.
    if (source.closed) source.off('error', captureError);
    else source.once('close', () => source.off('error', captureError));
  }
}

export async function readPrivateJson(filename: string): Promise<any> {
  const handle = await fs.open(filename, constants.O_RDONLY | constants.O_NOFOLLOW);
  try {
    const stat = await handle.stat();
    if (!stat.isFile() || stat.size > 64 * 1024 || (process.getuid && stat.uid !== process.getuid())) throw new Error('Unsafe attachment metadata.');
    const data = Buffer.alloc(64 * 1024 + 1);
    let bytesRead = 0;
    while (bytesRead < data.length) {
      const chunk = await handle.read(data, bytesRead, data.length - bytesRead, bytesRead);
      if (!chunk.bytesRead) break;
      bytesRead += chunk.bytesRead;
    }
    if (bytesRead > 64 * 1024) throw new Error('Attachment metadata exceeds its limit.');
    return JSON.parse(data.subarray(0, bytesRead).toString('utf8'));
  } finally { await handle.close(); }
}

export function readOwnedFile(filename: string): Readable {
  return createReadStream(filename, { fd: openSync(filename, constants.O_RDONLY | constants.O_NOFOLLOW), autoClose: true });
}
